all:
  hosts:
    k8s-1:
      ansible_host: 192.168.56.101
      ip: 192.168.56.101
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/k8s-1/virtualbox/private_key
    k8s-2:
      ansible_host: 192.168.56.102
      ip: 192.168.56.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/k8s-2/virtualbox/private_key

  children:
    kube_control_plane:
      hosts:
        k8s-1:
    kube_node:
      hosts:
        k8s-1:
        k8s-2:
    etcd:
      hosts:
        k8s-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
