Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Nodo master
  config.vm.define "k8s-1" do |node|
    node.vm.hostname = "k8s-1"
    node.vm.network "private_network", ip: "192.168.56.101"
    node.vm.network "forwarded_port", guest: 8001, host: 8001
    
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-1"
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y python3 python3-pip sshpass
    SHELL
  end

  # Nodo worker
  config.vm.define "k8s-2" do |node|
    node.vm.hostname = "k8s-2"
    node.vm.network "private_network", ip: "192.168.56.102"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-2"
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y python3 python3-pip sshpass
    SHELL
  end
end
